server:
  port: 8081
soap:
  external:
    susalud:
      endpoint: "http://localhost:8088/ws-consulta-afiliados/services"
logging:
  level:
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.client.MessageTracing.received: TRACE